# Generated by Django 3.0.3 on 2020-09-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default=int, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(max_length=500),
        ),
    ]
