# Generated by Django 2.1 on 2020-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
